language: php

php:
  - 5.5
  - 5.6
  - 7

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS `laravel-admin`;"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit